source 'https://rubygems.org'

# Use local clones if possible.
# If you want to use your local copy, just symlink it to vendor
def custom_gem(name, options = Hash.new)
  local_path = File.expand_path "../vendor/#{name}", __FILE__

  if File.exist? local_path
    options = options.merge :path => local_path
    options.delete_if do |key, _|
      [:github, :branch].include? key
    end
  end

  gem name, options
end

custom_gem 'synapse-core', :github => 'ianunruh/synapse', :branch => :master
custom_gem 'synapse-mongo', :github => 'ianunruh/synapse-mongo', :branch => :master

gem 'activemodel'
gem 'bson_ext', :platform => :ruby
gem 'ox', :platform => :ruby
