require 'synapse/configuration/container'
require 'synapse/configuration/container_builder'
require 'synapse/configuration/definition'
require 'synapse/configuration/definition_builder'
require 'synapse/configuration/dependent'
require 'synapse/configuration/extension'

require 'synapse/configuration/component/shared/thread_pool'
require 'synapse/configuration/component/command_bus'
require 'synapse/configuration/component/event_bus'
# Has to be loaded before event sourcing
require 'synapse/configuration/component/repository'
require 'synapse/configuration/component/event_sourcing'
require 'synapse/configuration/component/process_manager'
require 'synapse/configuration/component/serialization'
require 'synapse/configuration/component/uow'
require 'synapse/configuration/component/upcasting'
